name: "Auto assign maintainer to issue"
on:
  issues:
    types: [opened]

permissions: {}

jobs:
  assign-maintainer:
    uses: grafana/k6/.github/workflows/issue-auto-assign.yml@2ac2bb560e70b33735692642231c8bd53acbe4fd  # v1.6.1
    permissions:
      issues: write