name: "Auto assign maintainer to issue"
on:
  issues:
    types: [opened]

permissions: {}

jobs:
  assign-maintainer:
    uses: grafana/k6/.github/workflows/issue-auto-assign.yml@e0887846143ab176d4b5483c9d52cf3b3e009f1a  # v2.3.0
    permissions:
      issues: write