name: "Auto assign maintainer to issue"
on:
  issues:
    types: [opened]

permissions: {}

jobs:
  assign-maintainer:
    uses: grafana/k6/.github/workflows/issue-auto-assign.yml@7961cefa120dc673ae1fec6a77a456e2e1cb5e65  # v1.5.0
    permissions:
      issues: write